const bgStylePokemonType = {
    normal: "bg-gradient-to-b from-normal to-normal/40",
    fire: "bg-gradient-to-b from-fire to-fire/40",
    fighting: "bg-gradient-to-b from-fighting to-fighting/40",
    water: "bg-gradient-to-b from-water to-water/40",
    flying: "bg-gradient-to-b from-flying to-flying/40",
    grass: "bg-gradient-to-b from-grass to-grass/40",
    poison: "bg-gradient-to-b from-poison to-poison/40",
    electric: "bg-gradient-to-b from-electric to-electric/40",
    ground: "bg-gradient-to-b from-ground to-ground/40",
    psychic: "bg-gradient-to-b from-psychic to-psychic/40",
    rock: "bg-gradient-to-b from-rock to-rock/40",
    ice: "bg-gradient-to-b from-ice to-ice/40",
    bug: "bg-gradient-to-b from-bug to-bug/40",
    dragon: "bg-gradient-to-b from-dragon to-dragon/40",
    ghost: "bg-gradient-to-b from-ghost to-ghost/40",
    dark: "bg-gradient-to-b from-dark to-dark/40",
    steel: "bg-gradient-to-b from-steel to-steel/40",
    fairy: "bg-gradient-to-b from-fairy to-fairy/40",
    unkown: "bg-gradient-to-b from-unkown to-unkown/40",
    shadow: "bg-gradient-to-b from-shadow to-shadow/40",
  };

  const borderStylePokemonType = {
    normal: "border-normal/70",
    fire: "border-fire/70",
    fighting: "border-fighting/70",
    water: "border-water/70",
    flying: "border-flying/70",
    grass: "border-grass/70",
    poison: "border-poison/70",
    electric: "border-electric/70",
    ground: "border-ground/70",
    psychic: "border-psychic/70",
    rock: "border-rock/70",
    ice: "border-ice/70",
    bug: "border-bug/70",
    dragon: "border-dragon/70",
    ghost: "border-ghost/70",
    dark: "border-dark/70",
    steel: "border-steel/70",
    fairy: "border-fairy/70",
    unkown: "border-unkown/70",
    shadow: "border-shadow/70",
  };

  const flatBgStylePokemonType = {
    normal: "bg-normal",
    fire: "bg-fire",
    fighting: "bg-fighting",
    water: "bg-water",
    flying: "bg-flying",
    grass: "bg-grass",
    poison: "bg-poison",
    electric: "bg-electric",
    ground: "bg-ground",
    psychic: "bg-psychic",
    rock: "bg-rock",
    ice: "bg-ice",
    bug: "bg-bug",
    dragon: "bg-dragon",
    ghost: "bg-ghost",
    dark: "bg-dark",
    steel: "bg-steel",
    fairy: "bg-fairy",
    unkown: "bg-unkown",
    shadow: "bg-shadow",
  };

  export{bgStylePokemonType,
borderStylePokemonType,
flatBgStylePokemonType}